/*
 * Medical managment API
 *
 * Medical managment API for hospital staff and treatments managment
 *
 * OpenAPI spec version: 1.0.0
 * Contact: matej.mikus96@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Eu.InCloud.Medical.Management.Models;

namespace Eu.InCloud.Medical.Management.Dtos
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class EmployeeEnumsDto
    { 
        /// <summary>
        /// Gets or Sets MaritalStatus
        /// </summary>
        [DataMember(Name="maritalStatus")]
        public List<EnumModel> MaritalStatus { get; set; }

        /// <summary>
        /// Gets or Sets Roles
        /// </summary>
        [DataMember(Name="roles")]
        public List<EnumModel> Roles { get; set; }

        /// <summary>
        /// Gets or Sets EducationalLevel
        /// </summary>
        [DataMember(Name="educationalLevels")]
        public List<EnumModel> EducationalLevels { get; set; }

        /// <summary>
        /// Gets or Sets gender enums
        /// </summary>
        [DataMember(Name="genders")]
        public List<EnumModel> Genders { get; set; }
    }
}
