/*
 * Medical managment API
 *
 * Medical managment API for hospital staff and treatments managment
 *
 * OpenAPI spec version: 1.0.0
 * Contact: matej.mikus96@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Eu.InCloud.Medical.Management.Models;

namespace Eu.InCloud.Medical.Management.Dtos
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class TreatmentEnumsDto
    { 
        /// <summary>
        /// Gets or Sets TreatmentTypes
        /// </summary>
        [DataMember(Name="treatmentTypes")]
        public List<EnumModel> TreatmentTypes { get; set; }

        /// <summary>
        /// Gets or Sets TreatmentStatus
        /// </summary>
        [DataMember(Name="treatmentStatus")]
        public List<EnumModel> TreatmentStatus { get; set; }
    }
}
